apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: devops-container
        image: baraishubham78/harness-project:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret

        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
