name: Full CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install Dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: ./app

      # 4. Run Tests
      - name: Run Tests
        run: npm test
        working-directory: ./app

      # 5. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Build Image
      - name: Build Docker Image
        run: docker build -t harness-project:latest -f docker/Dockerfile .

      # 7. Tag Image
      - name: Tag Image
        run: docker tag harness-project:latest baraishubham78/harness-project:latest

      # 8. Push Image
      - name: Push Image
        run: docker push baraishubham78/harness-project:latest

  deploy:
  runs-on: [self-hosted, Windows, X64]
  needs: build-and-push

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/devops-app devops-container=baraishubham78/harness-project:latest
        kubectl rollout status deployment/devops-app