name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install
      - name: Install Dependencies
        run: npm install
        working-directory: app

      # 4. Test
      - name: Run Tests
        run: npm test
        working-directory: app

      # 5. Build Docker Image
      - name: Build Docker Image
        run: docker build -t devops-app:latest -f docker/Dockerfile .

      # 6. Verify
      - name: List Images
        run: docker images
